In [1]:
import pandas as pd

In [21]:
# Data set import
bios = pd.read_excel('./data/olympics-data.xlsx')
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [ ]:
# Filtering the data
# Get the name and height for players taller than 215cm, both are the same but diff syntax
bios.loc[bios['height_cm'] > 215, ['name', 'height_cm']]
bios[bios['height_cm' ] > 215][['name', 'height_cm']]

# Multiple conditions, height above 215 and born country USA
bios.loc[(bios['height_cm'] > 215) & (bios['born_country']=='USA')]

# Seeing if a string contains something, then if so output name and home country
bios.loc[bios['name'].str.contains("Keith"), ['name', 'born_country']]

# Keith OR Patrick
bios.loc[bios['name'].str.contains("Keith|Patrick"), ['name', 'born_country']]

# Keith OR Patrick, output in decending order from date died
bios.loc[bios['name'].str.contains("Keith|Patrick"), 
         ['name', 'died_date', 'born_country']].sort_values('died_date', ascending=False)

# Records with one of these countries, then see if we have a first name Keith
# Then output name, born country, and birthday (oldest to youngest)
bios.loc[bios['born_country'].isin(["USA", "FRA", "GBR"]) 
         & (bios['name'].str.startswith("Keith")), 
         ['name', 'born_country', 'born_date']].sort_values('bor')

                      name born_country   born_date
3505         Keith Wallace          GBR  1961-03-29
12053         Keith Hervey          GBR  1898-11-03
14577       Keith Harrison          GBR  1933-03-28
16166       Keith Reynolds          GBR  1963-12-25
18734       Keith Sinclair          GBR  1945-06-26
29897        Keith Langley          GBR  1961-06-03
34011         Keith Remfry          GBR  1947-11-17
46885         Keith Collin          GBR  1937-01-18
50929         Keith Carter          USA  1924-08-30
51185        Keith Russell          USA  1948-01-15
52913       Keith Erickson          USA  1944-04-19
55317         Keith Boxell          GBR  1958-05-06
57818         Keith Peache          GBR  1947-08-10
61748        Keith Grogono          GBR  1912-11-04
62620          Keith Musto          GBR  1936-01-12
62678         Keith Notary          USA  1960-01-22
68324          Keith Angus          GBR  1943-04-05
68472         Keith Cullen          GBR  1972-06-13
68997          Keith Stock          GBR  1957-03-18
77550        Keith Brantly          USA  1962-05-23
84097   Keith Christiansen          USA  1944-07-14
94646          Keith Meyer          USA  1938-06-20
95267         Keith Oliver          GBR  1947-10-27
96452   Keith Schellenberg          GBR  1929-03-13
97499        Keith Tkachuk          USA  1972-03-28
98068        Keith Wegeman          USA  1929-08-28
99921         Keith Carney          USA  1970-02-03
115973     Keith Sanderson          USA  1975-02-02